language: node_js
node_js:
  - "7"
cache: npm
install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: publish
      script:
        - ./now_deploy.sh

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/
  - provider: pages
    local_dir: ./build/
    skip_cleanup: true